### ISSUE TITLE
Anki Popup

### ISSUE THREAD

**Issue by nyxaria** [shigeyukey/my_addons#25]
Hi, great addon thank you for your work! Would it be possible to get the source code for this please?

I would like to modify it so that the "Start Review" popup doesn't show up and instead Anki reappears and goes to the next card directly.

Thank you!

**Comment by nyxaria** [comment]
Ok I got it: in __init__.py lines 206:
location of file: /Users/georgehartt/Library/Application Support/Anki2

change 
```

    if not mw.isActiveWindow() or mw.isMinimized():
        dialog = SimpleDialog()
        dialog.show()
```
to
```

    if not mw.isActiveWindow() or mw.isMinimized():
        Ankipopup_mw_show()
```

**Comment by shigeyukey** [comment]
Thanks for the code suggestion! :-)
This action was intentional, because if a card suddenly shows up while I'm programming, I may accidentally press enter to answer it. So I have disabled the key input in the popup.
For now, I am developing a prototype that will disable key input without showing a popup. But I think it will still take some time.
